Import PDF Document :

In [1]:
import os 
import requests

pdf_path = "knowledge_base/artificial_intelligence_technology.pdf"

if not os.path.exists(pdf_path):
  print(f"[Info] file doesn't exist, downloading... ")

  #Enter the url of the pdf 
  url = "https://link.springer.com/content/pdf/10.1007/978-981-19-2879-6.pdf"

  # Local filename to save the downloaded file 
  file_name = pdf_path

  # Send a GET request to the url 
  response = requests.get(url , timeout=5)

  # check if the request was successful
  if response.status_code == 200:
    # Open the file and save it 
    with open (file_name,"wb") as  file:
      file.write(response.content)
    print(f"[Info] the file has been downloaded and saved as {file_name}")

  else:
    print(f"[Info] Failed to download the file. Status code: {response.status_code}")
else:
  print(f"File {pdf_path} Exists.")

File knowledge_base/artificial_intelligence_technology.pdf Exists.

Ingestion / Open the pdf and extract the text and metadata from the pdf:

In [11]:
import fitz
from tqdm.auto import tqdm

def text_format(text:str) -> str:
  """Performs minor formatting on text."""
  clear_text = text.replace("\n", " ").strip()
  # Other potential text formatting functions can go here
  return clear_text

# Open PDF and get lines/pages
# Note: this only focuses on text, rather than images/figures etc
def open_and_read_pdf(pdf_path : str)-> list[dict]:
  """
    Opens a PDF file, reads its text content page by page, and collects statistics.

    Parameters:
        pdf_path (str): The file path to the PDF document to be opened and read.

    Returns:
        list[dict]: A list of dictionaries, each containing the page number
        (adjusted), character count, word count, sentence count, token count, and the extracted text
        for each page.
    """
  doc = fitz.open(pdf_path) # Open a document
  pages_and_texts = []
  for page_number,page in tqdm(enumerate(doc,start=1)):
    text = page.get_text()
    # text = text_format(text)
    if not text:
      continue

    # pages_and_texts.append({"page_number": page_number - 13,  # adjust page numbers since our PDF starts on page 14
    #                             "page_char_count": len(text),
    #                             "page_word_count": len(text.split(" ")),
    #                             "page_sentence_count_raw": len(text.split(". ")),
    #                             "page_token_count": len(text) / 4,  # 1 token = ~4 chars,
    #                             "text": text})
    pages_and_texts.append({"text": text,
                            "metadata":{
                              "source": pdf_path,
                              "pdf_page": page_number,
                              "page_label": page.get_label()
                            }})
  return pages_and_texts
pages_and_texts = open_and_read_pdf("knowledge_base/artificial_intelligence_technology.pdf")
print(len(pages_and_texts))
print(pages_and_texts[0])
print(pages_and_texts[13])
print(pages_and_texts[-1])
print(pages_and_texts[18])
print(pages_and_texts[31])

0it [00:00, ?it/s]

308it [00:01, 179.71it/s]

308
{'text': 'Official Textbooks for Huawei ICT Academy\nARTIFICIAL \nINTELLIGENCE \nTECHNOLOGY\nHuawei Technologies Co., Ltd.\n', 'metadata': {'source': 'knowledge_base/artificial_intelligence_technology.pdf', 'pdf_page': 1, 'page_label': 'C1'}}
{'text': 'Chapter 1\nA General Introduction to Artiﬁcial\nIntelligence\nThe emergence and rise of artiﬁcial intelligence undoubtedly played an important\nrole during the development of the Internet. Over the past decade, with extensive\napplications in the society, artiﬁcial intelligence has become more relevant to\npeople’s daily life. This chapter introduces the concept of artiﬁcial intelligence, the\nrelated technologies, and the existing controversies over the topic.\n1.1\nThe Concept of Artiﬁcial Intelligence\n1.1.1\nWhat Is Artiﬁcial Intelligence?\nCurrently, people mainly learn about artiﬁcial intelligence (AI) through news,\nmovies, and the applications in daily life, as shown by Fig. 1.1.\nA rather widely accepted deﬁnition of AI, also a relatively early one, was\nproposed by John McCarthy at the 1956 Dartmouth Conference, which outlined\nthat artiﬁcial intelligence is about letting a machine simulate the intelligent behavior\nof humans as precisely as it can be. However, this deﬁnition seemingly ignores the\npossibility of strong artiﬁcial intelligence (which means the machine that has the\nability or intelligence to solve problems by reasoning).\nBefore explaining what “artiﬁcial intelligence” is, we had better clarify the\nconcept of “intelligence” ﬁrst.\nAccording to the theory of multiple intelligences, human intelligence can be\ncategorized into seven types: Linguistic, Logical-Mathematical, Spatial Bodily-\nKinesthetic, Musical, Interpersonal and Intrapersonal intelligence.\n1. Linguistic Intelligence\nLinguistic intelligence refers to the ability to effectively express one’s\nthoughts in spoken or written language, understand others’ words or texts,\nﬂexibly master the phonology, semantics, and grammar of a language, manage\n© The Author(s) 2023\nHuawei Technologies Co., Ltd., Artiﬁcial Intelligence Technology,\nhttps://doi.org/10.1007/978-981-19-2879-6_1\n1\n', 'metadata': {'source': 'knowledge_base/artificial_intelligence_technology.pdf', 'pdf_page': 14, 'page_label': '1'}}
{'text': 'Huawei CLOUD EI agent, 240\nHuawei HiAI, vi, 23, 221–238\nHuawei HiAI Engine, 226, 227, 229, 234, 235,\n237\nHuawei HiAI Foundation, 224, 225, 229, 237\nHuawei HiLens, 245–249\nI\nIntegrated learning, 79, 105\nIntelligences, v, vi, 1–3, 5–7, 10, 12, 14, 23–25,\n28, 32, 36, 39, 79, 89, 105, 214, 216,\n238–281\nK\nK-nearest neighbor algorithm (KNN), 13, 63,\n76–77, 86\nL\nLinear regression, 63, 67–72, 83, 85, 86, 97,\n102, 112\nLogistic regression, 63, 71–72, 86, 99\nLoss function, 64, 69, 70, 72, 83–85, 93–94,\n97–99, 105, 107, 130, 131, 133, 134,\n150, 152, 157\nM\nMachine learning, v, 4–5, 7, 8, 13, 14, 21, 25,\n28, 32, 37, 40, 43–90, 93, 97, 101, 121,\n123, 133, 134, 140, 239, 278\nMachine learning algorithms, 13, 25, 43–46,\n59, 63, 66, 76, 86, 87, 97, 123\nMindspore, vi, 14, 32, 34, 35, 123–126,\n137–162, 211\nModelarts, 33, 34, 239, 261–267, 279, 281\nN\nNaive Bayes, 78–79, 86\nNatural language processing (NLP), 11, 14, 25,\n28, 34, 35, 38, 87, 109, 142, 239, 252,\n278\nNeural network software ﬂow, 171–173, 218,\n219\nO\nOptimizer, vi, 14, 106–109, 122, 131, 133, 134,\n150, 152, 157, 158\nP\nPerceptron algorithm, 89–93\nProcess choreographer, 169, 179\nPyTorch, 15, 35, 123–124, 127, 140, 141\nR\nRecurrent neural network (RNN), 13, 90, 108,\n109, 114–118, 121, 122, 129, 130\nRegularization, vi, 56, 59, 70, 101–105, 121,\n122\nReinforcement learning, 14, 16, 28, 38, 47,\n51–52\nS\nSemi-supervised learning, 47, 50\nSpeech processing, 25\nStrong artiﬁcial intelligence, 1, 5\nSupervised learning, 47–48, 50, 51, 56, 67, 82\nSupport vector machine (SVM), vi, 13, 63,\n75–76, 86, 90, 97\nSymbolism, 12\nT\nTask scheduler, 167, 170–172, 181–184, 186,\n195, 196\nTensor acceleration engine, 170\nTensor ﬂow, vi, 14, 15, 17, 35, 123, 124,\n126–135, 140–142, 144, 169, 211, 226,\n229, 230, 261, 264\nU\nUnsupervised learning, 47–51\nW\nWeak artiﬁcial intelligence, 5\n298\nIndex\n', 'metadata': {'source': 'knowledge_base/artificial_intelligence_technology.pdf', 'pdf_page': 308, 'page_label': '298'}}
{'text': 'machines with real human intelligence was possible in the future. But up to now,\nnone of the computers has ever passed the Turing Test.\nAlthough AI is a concept with a history of only a few decades, the theoretical\nfoundation and supporting technology behind it have developed for a time-honored\nperiod. The current prosperity of AI is a result of the advancement of all related\ndisciplines and the collective efforts of the scientists of all generations.\n1. Precursors and Initiation Period (before 1956)\nThe theoretical foundation for the birth of AI can date back to as early as the\nfourth century BC, when the famous ancient Greek philosopher and scientist\nAristotle invented the concept of formal logic. In fact, his theory of syllogism is\nstill working as an indispensable and decisive cornerstone for the deductive\nreasoning today. In the seventeenth century, the German mathematician Gottfried\nLeibniz advanced universal notation and some revolutionary ideas on reasoning\nand calculation, which laid the foundation for the establishment and development\nof mathematical logic. In the nineteenth century, the British mathematician\nGeorge Boole developed Boolean algebra, which is the bedrock of the operation\nof modern computers, and its introduction makes the invention of computer\nFig. 1.4 A brief history of AI\n6\n1\nA General Introduction to Artiﬁcial Intelligence\n', 'metadata': {'source': 'knowledge_base/artificial_intelligence_technology.pdf', 'pdf_page': 19, 'page_label': '6'}}
{'text': 'GPUs are good at dealing with operations that are intensive and easy to be run in\nparallel, while CPUs excel at logic control and serial operations.\nThe difference in architecture between GPU and CPU is because that they\nhave different emphasis. The GPU has an outstanding advantage in processing\nthe parallel computing of large-scale intensive data, while CPU more stresses the\nlogic control while executing the instructions. In order to optimize a program, it\noften needs to coordinate both CPU and GPU at the same time to give a full play\nto their capabilities.\n4. Huawei Ascend AI Processor\nNPU refers to the processor carrying out the optimization design specialized\nfor neural network computing, whose performance of neural network tasks\nprocessing is much higher than that of CPU and GPU.\nThe NPU mimics human neurons and synapses on the circuitry, and directly\nprocesses large scale neurons and synapses through deep learning processor\ninstruction set. In NPUs, the processing of a group of neurons will take only\none instruction. Currently, the typical examples of NPU include Huawei Ascend\nAI processor, the Cambrian chip and IBM’s TrueNorth chip.\nThere are two kinds of Huawei Ascend AI processor: Ascend 310 and Ascend 910.\nAscend 910 is mainly applied to training scenarios, mostly deployed in the data\ncenter. While Ascend 310 is mainly designed for reasoning scenarios, whose\ndeployment covers the device, edge and cloud full scenarios.\nAscend 910 is currently the AI processor with the strongest computing power and\nfastest training speed in the world, its computing power is twice that of the interna-\ntional top AI processor, equivalent to 50 latest and strongest CPUs today.\nThe relevant parameters of Ascend 310 and Ascend 910 are shown in Table 1.1.\nTable 1.1 The relevant parameters of Ascend 310 and Ascend 910\nAscend 310\nAscend 910\nChip: Ascend-Mini\nArchitecture: Da Vinci\n16-bit ﬂoating point precision (FP16) perfor-\nmance: 8 TFLOPS\n8-bit integer precision (INT8) performance:\n16 TOPS\n16 channel full HD video decoder\n–\nH.264/265\n1 channel full HD video encoder\n–\nH.264/265\nMaximum power consumption: 8 W\nProcess: 12 nm FFC\nChip: Ascend-Max\nArchitecture: Da Vinci\n16-bit ﬂoating point precision (FP16) perfor-\nmance: 256 TFLOPS\n8-bit integer precision (INT8) performance:\n512 TOPS\n128 channel full HD video decoder\n–\nH.264/265\nMaximum power consumption: 350 W\nProcess: 7 nm\n1.2\nAI-Related Technologies\n19\n', 'metadata': {'source': 'knowledge_base/artificial_intelligence_technology.pdf', 'pdf_page': 32, 'page_label': '19'}}

In [12]:
doc = fitz.open("knowledge_base/artificial_intelligence_technology.pdf")

page = doc[31]

data = page.get_text("dict")

for block_no, block in enumerate(data["blocks"]):

    if "lines" not in block:
        continue

    print(f"\n========== BLOCK {block_no} ==========")

    for line in block["lines"]:

        line_text = ""

        for span in line["spans"]:
            line_text += span["text"]

        print(
            f"y={line['bbox'][1]:.1f} "
            f"→ {repr(line_text)}"
        )

        for span in line["spans"]:
            print(
                f"    text={repr(span['text'])} | "
                f"size={span['size']} | "
                f"font={span['font']} | "
                f"flags={span['flags']}"
            )

========== BLOCK 0 ==========
y=225.6 → 'GPUs are good at dealing with operations that are intensive and easy to be run in'
    text='GPUs are good at dealing with operations that are intensive and easy to be run in' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=237.6 → 'parallel, while CPUs excel at logic control and serial operations.'
    text='parallel, while CPUs excel at logic control and serial operations.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 1 ==========
y=249.6 → 'The difference in architecture between GPU and CPU is because that they'
    text='The' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='difference' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='in' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='architecture' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='between' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='GPU' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='and' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='CPU' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='is' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='because' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='that' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='they' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=261.5 → 'have different emphasis. The GPU has an outstanding advantage in processing'
    text='have' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='different' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='emphasis.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='The' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='GPU' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='has' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='an' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='outstanding' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='advantage' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='in' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='processing' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=273.4 → 'the parallel computing of large-scale intensive data, while CPU more stresses the'
    text='the parallel computing of large-scale intensive data, while CPU more stresses the' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=285.4 → 'logic control while executing the instructions. In order to optimize a program, it'
    text='logic control while executing the instructions. In order to optimize a program, it' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=297.4 → 'often needs to coordinate both CPU and GPU at the same time to give a full play'
    text='often needs to coordinate both CPU and GPU at the same time to give a full play' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=309.3 → 'to their capabilities.'
    text='to their capabilities.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=321.3 → '4. Huawei Ascend AI Processor'
    text='4.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='Huawei Ascend AI Processor' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=333.3 → 'NPU refers to the processor carrying out the optimization design specialized'
    text='NPU' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='refers' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='to' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='the' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='processor' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='carrying' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='out' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='the' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='optimization' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='design' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='specialized' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=345.2 → 'for neural network computing, whose performance of neural network tasks'
    text='for' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='neural' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='network' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='computing,' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='whose' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='performance' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='of' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='neural' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='network' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='tasks' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=357.2 → 'processing is much higher than that of CPU and GPU.'
    text='processing is much higher than that of CPU and GPU.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 2 ==========
y=369.1 → 'The NPU mimics human neurons and synapses on the circuitry, and directly'
    text='The' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='NPU' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='mimics' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='human' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='neurons' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='and' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='synapses' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='on' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='the' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='circuitry,' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='and' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='directly' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=381.1 → 'processes large scale neurons and synapses through deep learning processor'
    text='processes' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='large' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='scale' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='neurons' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='and' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='synapses' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='through' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='deep' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='learning' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='processor' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=393.0 → 'instruction set. In NPUs, the processing of a group of neurons will take only'
    text='instruction' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='set.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='In' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='NPUs,' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='the' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='processing' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='of' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='a' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='group' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='of' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='neurons' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='will' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='take' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='only' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=405.0 → 'one instruction. Currently, the typical examples of NPU include Huawei Ascend'
    text='one instruction. Currently, the typical examples of NPU include Huawei Ascend' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=416.5 → 'AI processor, the Cambrian chip and IBM’s TrueNorth chip.'
    text='AI processor, the Cambrian chip and IBM' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='’' | size=9.962599754333496 | font=AdvTT5843c571+20 | flags=4
    text='s TrueNorth chip.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 3 ==========
y=434.9 → 'There are two kinds of Huawei Ascend AI processor: Ascend 310 and Ascend 910.'
    text='There are two kinds of Huawei Ascend AI processor: Ascend 310 and Ascend 910.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 4 ==========
y=446.8 → 'Ascend 910 is mainly applied to training scenarios, mostly deployed in the data'
    text='Ascend' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='910 is mainly applied' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='to training scenarios, mostly deployed in the data' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=458.8 → 'center. While Ascend 310 is mainly designed for reasoning scenarios, whose'
    text='center.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='While' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='Ascend' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='310' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='is' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='mainly' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='designed' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='for' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='reasoning' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='scenarios,' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' ' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='whose' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=470.8 → 'deployment covers the device, edge and cloud full scenarios.'
    text='deployment covers the device, edge and cloud full scenarios.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 5 ==========
y=482.7 → 'Ascend 910 is currently the AI processor with the strongest computing power and'
    text='Ascend 910 is currently the AI processor with the strongest computing power and' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=494.7 → 'fastest training speed in the world, its computing power is twice that of the interna-'
    text='fastest training speed in the world, its computing power is twice that of the interna-' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
y=506.7 → 'tional top AI processor, equivalent to 50 latest and strongest CPUs today.'
    text='tional top AI processor, equivalent to 50 latest and strongest CPUs today.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 6 ==========
y=518.6 → 'The relevant parameters of Ascend 310 and Ascend 910 are shown in Table 1.1.'
    text='The relevant parameters of Ascend 310 and Ascend 910 are shown in Table' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text=' 1.1' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4
    text='.' | size=9.962599754333496 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 7 ==========
y=61.7 → 'Table 1.1 The relevant parameters of Ascend 310 and Ascend 910'
    text='Table 1.1' | size=8.468199729919434 | font=AdvOTf9b4e953.B2 | flags=4
    text=' ' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
    text='The relevant parameters of Ascend 310 and Ascend 910' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4

========== BLOCK 8 ==========
y=76.7 → 'Ascend 310'
    text='Ascend 310' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=76.7 → 'Ascend 910'
    text='Ascend 910' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=89.1 → 'Chip: Ascend-Mini'
    text='Chip: Ascend-Mini' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=99.1 → 'Architecture: Da Vinci'
    text='Architecture: Da Vinci' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=108.7 → '16-bit ﬂoating point precision (FP16) perfor-'
    text='16-bit' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
    text=' ﬂ' | size=8.468199729919434 | font=AdvOTab62ddd1+fb2 | flags=4
    text='oating point precision (FP16) perfor-' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=119.0 → 'mance: 8 TFLOPS'
    text='mance: 8 TFLOPS' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=129.0 → '8-bit integer precision (INT8) performance:'
    text='8-bit integer precision (INT8) performance:' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=138.9 → '16 TOPS'
    text='16 TOPS' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=148.9 → '16 channel full HD video decoder'
    text='16 channel full HD video decoder' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=158.5 → '–'
    text='–' | size=8.468199729919434 | font=AdvOTab62ddd1+202 | flags=4
y=158.8 → 'H.264/265'
    text='H.264/265' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=168.8 → '1 channel full HD video encoder'
    text='1 channel full HD video encoder' | size=8.468199729919434 | font=AdvOTab62ddd12 | flags=4
y=178.4 → '–'

In [3]:
doc = fitz.open("knowledge_base/artificial_intelligence_technology.pdf")

print("Total PDF pages:",len(doc))
print("Extracted pages:",len(pages_and_texts))

Total PDF pages: 308
Extracted pages: 308

In [5]:
# print(pages_and_texts[0]["metadata"])
# print(pages_and_texts[12]["metadata"])
# print(pages_and_texts[13]["metadata"])
# print(pages_and_texts[-1]["metadata"])

Get some stats on the text

In [6]:
import pandas as pd 

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-12,108,15,1,27.00,Official Textbooks for Huawei ICT Academy ARTI...
1,-11,33,3,1,8.25,Artiﬁcial Intelligence Technology
2,-10,63,7,2,15.75,"Huawei Technologies Co., Ltd. Artiﬁcial Intell..."
3,-9,2976,445,20,744.00,"Huawei Technologies Co., Ltd. Hangzhou, China ..."
4,-8,2389,377,14,597.25,Preface The rapid development of information t...

In [8]:
df.describe()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,308.000000,308.00000,308.000000,308.000000,308.000000
mean,141.500000,1908.36039,307.519481,32.775974,477.090097
std,89.056162,747.83511,160.649850,122.403369,186.958778
min,-12.000000,33.00000,3.000000,1.000000,8.250000
25%,64.750000,1478.75000,221.750000,13.000000,369.687500
50%,141.500000,1878.50000,294.500000,16.000000,469.625000
75%,218.250000,2478.25000,388.000000,21.000000,619.562500
max,295.000000,3747.00000,1392.000000,1183.000000,936.750000